version: '3.7'

services:
  client:
    container_name: exercice-client
    build:
      context: ./exercice-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development